<?php

namespace Database\Seeders;

use App\Models\AdmissionApplication;
use App\Models\Grade;
use App\Models\Level;
use Illuminate\Database\Seeder;

class AdmissionApplicationSeeder extends Seeder
{
    public function run(): void
    {
        $basicLevel = Level::where('level_name', 'Básicos')->first();
        $divLevel = Level::where('level_name', 'Diversificado')->first();

        $primero = Grade::where('grade_name', 'Primero Básico')->first();
        $segundo = Grade::where('grade_name', 'Segundo Básico')->first();
        $tercero = Grade::where('grade_name', 'Tercero Básico')->first();
        $cuartoBach = Grade::where('grade_name', 'Cuarto Bachillerato en Ciencias y Letras')->first();
        $quintoBach = Grade::where('grade_name', 'Quinto Bachillerato en Ciencias y Letras')->first();

        $year = now()->month <= 6 ? now()->year : now()->addYear()->year;

        $applications = [
            [
                'year' => $year,
                'level_id' => $basicLevel->id,
                'grade_id' => $primero->id,
                'student_first_name' => 'Carlos',
                'student_second_name' => 'Alejandro',
                'student_first_surname' => 'Ramírez',
                'student_second_surname' => 'López',
                'student_birthdate' => '2012-07-15',
                'student_address' => '4ta. Avenida 12-34 Zona 3, Guatemala',
                'student_previous_school' => 'Escuela Primaria San José',
                'student_religion' => 'Católica',
                'father_first_name' => 'Roberto',
                'father_last_name' => 'Ramírez García',
                'father_phone' => '55123456',
                'father_workplace' => 'Banco Industrial S.A.',
                'father_nit' => '12345678-9',
                'father_profession' => 'Contador',
                'mother_first_name' => 'Ana',
                'mother_last_name' => 'López de Ramírez',
                'mother_phone' => '45678901',
                'mother_workplace' => 'Ministerio de Educación',
                'mother_nit' => '98765432-1',
                'mother_profession' => 'Maestra',
                'guardian_type' => 'father',
                'guardian_name' => 'Roberto Ramírez García',
                'guardian_phone' => '55123456',
                'guardian_nit' => null,
                'guardian_email' => 'rramirez@gmail.com',
                'referral_source' => 'Instagram',
                'sons_count' => 2,
                'sons_ages' => '13, 10',
                'daughters_count' => 1,
                'daughters_ages' => '7',
                'current_status' => 'pending',
                'ip_address' => '192.168.1.100',
            ],
            [
                'year' => $year,
                'level_id' => $divLevel->id,
                'grade_id' => $cuartoBach->id,
                'student_first_name' => 'María',
                'student_second_name' => 'Fernanda',
                'student_first_surname' => 'Morales',
                'student_second_surname' => 'Cifuentes',
                'student_birthdate' => '2009-03-22',
                'student_address' => '15 Calle 8-90 Zona 10, Guatemala',
                'student_previous_school' => 'Instituto Mixto Nocturno de Educación Básica',
                'student_religion' => 'Evangélica',
                'father_first_name' => 'Jorge',
                'father_last_name' => 'Morales Saenz',
                'father_phone' => '31456789',
                'father_workplace' => 'Constructora Morales S.A.',
                'father_nit' => '44556677-8',
                'father_profession' => 'Ingeniero Civil',
                'mother_first_name' => 'Silvia',
                'mother_last_name' => 'Cifuentes de Morales',
                'mother_phone' => '44567890',
                'mother_workplace' => 'Clínica Médica San Rafael',
                'mother_nit' => '33221100-5',
                'mother_profession' => 'Enfermera',
                'guardian_type' => 'mother',
                'guardian_name' => 'Silvia Cifuentes de Morales',
                'guardian_phone' => '44567890',
                'guardian_nit' => null,
                'guardian_email' => 'scifuentes@hotmail.com',
                'referral_source' => 'Facebook',
                'sons_count' => 0,
                'sons_ages' => null,
                'daughters_count' => 2,
                'daughters_ages' => '16, 12',
                'current_status' => 'pending',
                'ip_address' => '192.168.1.101',
            ],
            [
                'year' => $year,
                'level_id' => $basicLevel->id,
                'grade_id' => $segundo->id,
                'student_first_name' => 'Diego',
                'student_second_name' => 'Ernesto',
                'student_first_surname' => 'Hernández',
                'student_second_surname' => 'Méndez',
                'student_birthdate' => '2011-11-05',
                'student_address' => '6ta. Calle Final Colonia El Milagro, Zona 6, Guatemala',
                'student_previous_school' => 'Colegio Cristóbal Colón',
                'student_religion' => 'Católica',
                'father_first_name' => 'José',
                'father_last_name' => 'Hernández Torres',
                'father_phone' => '50234567',
                'father_workplace' => 'Importadora El Éxito',
                'father_nit' => '77889900-2',
                'father_profession' => 'Comerciante',
                'mother_first_name' => 'Carla',
                'mother_last_name' => 'Méndez de Hernández',
                'mother_phone' => '55345678',
                'mother_workplace' => null,
                'mother_nit' => null,
                'mother_profession' => 'Ama de casa',
                'guardian_type' => 'father',
                'guardian_name' => 'José Hernández Torres',
                'guardian_phone' => '50234567',
                'guardian_nit' => null,
                'guardian_email' => 'jhernandez.torres@gmail.com',
                'referral_source' => 'Referido por familiar',
                'sons_count' => 1,
                'sons_ages' => '13',
                'daughters_count' => 0,
                'daughters_ages' => null,
                'current_status' => 'pending',
                'ip_address' => '192.168.1.102',
            ],
            [
                'year' => $year,
                'level_id' => $divLevel->id,
                'grade_id' => $quintoBach->id,
                'student_first_name' => 'Andrea',
                'student_second_name' => 'Sofía',
                'student_first_surname' => 'Castellanos',
                'student_second_surname' => 'Vela',
                'student_birthdate' => '2008-06-18',
                'student_address' => '2da. Avenida 5-17 Zona 7 Colonia Landivar, Guatemala',
                'student_previous_school' => 'Instituto Nacional Central de Señoritas',
                'student_religion' => 'Católica',
                'father_first_name' => 'Alejandro',
                'father_last_name' => 'Castellanos Pineda',
                'father_phone' => '22334455',
                'father_workplace' => 'Superintendencia de Administración Tributaria (SAT)',
                'father_nit' => '11223344-6',
                'father_profession' => 'Auditor Fiscal',
                'mother_first_name' => 'Patricia',
                'mother_last_name' => 'Vela de Castellanos',
                'mother_phone' => '33445566',
                'mother_workplace' => 'Universidad de San Carlos de Guatemala',
                'mother_nit' => '66554433-0',
                'mother_profession' => 'Docente Universitaria',
                'guardian_type' => 'mother',
                'guardian_name' => 'Patricia Vela de Castellanos',
                'guardian_phone' => '33445566',
                'guardian_nit' => null,
                'guardian_email' => 'patriciavela.docente@gmail.com',
                'referral_source' => 'Cercanía',
                'sons_count' => 0,
                'sons_ages' => null,
                'daughters_count' => 2,
                'daughters_ages' => '17, 15',
                'current_status' => 'pending',
                'ip_address' => '192.168.1.103',
            ],
            [
                'year' => $year,
                'level_id' => $basicLevel->id,
                'grade_id' => $tercero->id,
                'student_first_name' => 'Luis',
                'student_second_name' => 'Fernando',
                'student_first_surname' => 'Ajú',
                'student_second_surname' => 'Tzunun',
                'student_birthdate' => '2010-09-30',
                'student_address' => 'Aldea San Marcos, Km 32, Carretera hacia San Juan Sacatepéquez',
                'student_previous_school' => 'Escuela Oficial Rural Mixta Aldea San Marcos',
                'student_religion' => 'Evangélica',
                'father_first_name' => null,
                'father_last_name' => null,
                'father_phone' => null,
                'father_workplace' => null,
                'father_nit' => null,
                'father_profession' => null,
                'mother_first_name' => 'Rosa',
                'mother_last_name' => 'Tzunun Ajú',
                'mother_phone' => '40123456',
                'mother_workplace' => 'Cooperativa Agrícola Regional',
                'mother_nit' => '55667788-3',
                'mother_profession' => 'Agricultora',
                'guardian_type' => 'mother',
                'guardian_name' => 'Rosa Tzunun Ajú',
                'guardian_phone' => '40123456',
                'guardian_nit' => null,
                'guardian_email' => 'rosa.tzunun@yahoo.com',
                'referral_source' => 'Referido por familia vecina',
                'sons_count' => 2,
                'sons_ages' => '15, 10',
                'daughters_count' => 1,
                'daughters_ages' => '8',
                'current_status' => 'pending',
                'ip_address' => '192.168.1.104',
            ],
        ];

        foreach ($applications as $data) {
            $app = AdmissionApplication::create($data);

            $app->statuses()->create(['status' => 'pending']);
            $app->documents()->create([]);
        }
    }
}
