<?php

namespace Database\Seeders;

use App\Models\ClassroomCourseAssignment;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassroomCourseAssignmentSeeder extends Seeder
{
    public function run(): void
    {
        $data = $this->getData();

        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('classroom_course_assignments')->insertOrIgnore($chunk);
        }
    }

    private function getData(): array
    {
        return [
            // ==========================================
            // CLASSROOM 1 — Primero Básico Sección A
            // Pénsum 1 — pensum_course_ids 1-11
            // ==========================================
            ['classroom_id' => 1, 'professor_id' => 1,  'pensum_course_id' => 1,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 1,  'pensum_course_id' => 1,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 1,  'pensum_course_id' => 1,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 1,  'pensum_course_id' => 1,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 12, 'pensum_course_id' => 2,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 12, 'pensum_course_id' => 2,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 12, 'pensum_course_id' => 2,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 12, 'pensum_course_id' => 2,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 7,  'pensum_course_id' => 3,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 7,  'pensum_course_id' => 3,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 7,  'pensum_course_id' => 3,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 7,  'pensum_course_id' => 3,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 8,  'pensum_course_id' => 4,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 8,  'pensum_course_id' => 4,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 8,  'pensum_course_id' => 4,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 8,  'pensum_course_id' => 4,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 12, 'pensum_course_id' => 5,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 12, 'pensum_course_id' => 5,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 12, 'pensum_course_id' => 5,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 12, 'pensum_course_id' => 5,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 3,  'pensum_course_id' => 6,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 3,  'pensum_course_id' => 6,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 3,  'pensum_course_id' => 6,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 3,  'pensum_course_id' => 6,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 7,  'pensum_course_id' => 7,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 7,  'pensum_course_id' => 7,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 7,  'pensum_course_id' => 7,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 7,  'pensum_course_id' => 7,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 10, 'pensum_course_id' => 8,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 10, 'pensum_course_id' => 8,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 10, 'pensum_course_id' => 8,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 10, 'pensum_course_id' => 8,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 8,  'pensum_course_id' => 9,  'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 8,  'pensum_course_id' => 9,  'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 8,  'pensum_course_id' => 9,  'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 8,  'pensum_course_id' => 9,  'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 11, 'pensum_course_id' => 10, 'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 11, 'pensum_course_id' => 10, 'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 11, 'pensum_course_id' => 10, 'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 11, 'pensum_course_id' => 10, 'unit' => 4],
            ['classroom_id' => 1, 'professor_id' => 5,  'pensum_course_id' => 11, 'unit' => 1],
            ['classroom_id' => 1, 'professor_id' => 5,  'pensum_course_id' => 11, 'unit' => 2],
            ['classroom_id' => 1, 'professor_id' => 5,  'pensum_course_id' => 11, 'unit' => 3],
            ['classroom_id' => 1, 'professor_id' => 5,  'pensum_course_id' => 11, 'unit' => 4],

            // ==========================================
            // CLASSROOM 2 — Primero Básico Sección B
            // Pénsum 1 — pensum_course_ids 1-11
            // ==========================================
            ['classroom_id' => 2, 'professor_id' => 1,  'pensum_course_id' => 1,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 1,  'pensum_course_id' => 1,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 1,  'pensum_course_id' => 1,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 1,  'pensum_course_id' => 1,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 12, 'pensum_course_id' => 2,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 12, 'pensum_course_id' => 2,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 12, 'pensum_course_id' => 2,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 12, 'pensum_course_id' => 2,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 4,  'pensum_course_id' => 3,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 4,  'pensum_course_id' => 3,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 4,  'pensum_course_id' => 3,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 4,  'pensum_course_id' => 3,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 8,  'pensum_course_id' => 4,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 8,  'pensum_course_id' => 4,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 8,  'pensum_course_id' => 4,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 8,  'pensum_course_id' => 4,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 12, 'pensum_course_id' => 5,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 12, 'pensum_course_id' => 5,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 12, 'pensum_course_id' => 5,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 12, 'pensum_course_id' => 5,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 3,  'pensum_course_id' => 6,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 3,  'pensum_course_id' => 6,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 3,  'pensum_course_id' => 6,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 3,  'pensum_course_id' => 6,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 9,  'pensum_course_id' => 7,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 9,  'pensum_course_id' => 7,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 9,  'pensum_course_id' => 7,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 9,  'pensum_course_id' => 7,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 10, 'pensum_course_id' => 8,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 10, 'pensum_course_id' => 8,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 10, 'pensum_course_id' => 8,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 10, 'pensum_course_id' => 8,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 8,  'pensum_course_id' => 9,  'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 8,  'pensum_course_id' => 9,  'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 8,  'pensum_course_id' => 9,  'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 8,  'pensum_course_id' => 9,  'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 11, 'pensum_course_id' => 10, 'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 11, 'pensum_course_id' => 10, 'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 11, 'pensum_course_id' => 10, 'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 11, 'pensum_course_id' => 10, 'unit' => 4],
            ['classroom_id' => 2, 'professor_id' => 5,  'pensum_course_id' => 11, 'unit' => 1],
            ['classroom_id' => 2, 'professor_id' => 5,  'pensum_course_id' => 11, 'unit' => 2],
            ['classroom_id' => 2, 'professor_id' => 5,  'pensum_course_id' => 11, 'unit' => 3],
            ['classroom_id' => 2, 'professor_id' => 5,  'pensum_course_id' => 11, 'unit' => 4],

            // ==========================================
            // CLASSROOM 3 — Segundo Básico Sección A
            // Pénsum 2 — pensum_course_ids 12-22
            // ==========================================
            ['classroom_id' => 3, 'professor_id' => 1,  'pensum_course_id' => 12, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 1,  'pensum_course_id' => 12, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 1,  'pensum_course_id' => 12, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 1,  'pensum_course_id' => 12, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 12, 'pensum_course_id' => 13, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 12, 'pensum_course_id' => 13, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 12, 'pensum_course_id' => 13, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 12, 'pensum_course_id' => 13, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 8,  'pensum_course_id' => 14, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 8,  'pensum_course_id' => 14, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 8,  'pensum_course_id' => 14, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 8,  'pensum_course_id' => 14, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 3,  'pensum_course_id' => 15, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 3,  'pensum_course_id' => 15, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 3,  'pensum_course_id' => 15, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 3,  'pensum_course_id' => 15, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 6,  'pensum_course_id' => 16, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 6,  'pensum_course_id' => 16, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 6,  'pensum_course_id' => 16, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 6,  'pensum_course_id' => 16, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 3,  'pensum_course_id' => 17, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 3,  'pensum_course_id' => 17, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 3,  'pensum_course_id' => 17, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 3,  'pensum_course_id' => 17, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 9,  'pensum_course_id' => 18, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 9,  'pensum_course_id' => 18, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 9,  'pensum_course_id' => 18, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 9,  'pensum_course_id' => 18, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 10, 'pensum_course_id' => 19, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 10, 'pensum_course_id' => 19, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 10, 'pensum_course_id' => 19, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 10, 'pensum_course_id' => 19, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 12, 'pensum_course_id' => 20, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 12, 'pensum_course_id' => 20, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 12, 'pensum_course_id' => 20, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 12, 'pensum_course_id' => 20, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 11, 'pensum_course_id' => 21, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 11, 'pensum_course_id' => 21, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 11, 'pensum_course_id' => 21, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 11, 'pensum_course_id' => 21, 'unit' => 4],
            ['classroom_id' => 3, 'professor_id' => 5,  'pensum_course_id' => 22, 'unit' => 1],
            ['classroom_id' => 3, 'professor_id' => 5,  'pensum_course_id' => 22, 'unit' => 2],
            ['classroom_id' => 3, 'professor_id' => 5,  'pensum_course_id' => 22, 'unit' => 3],
            ['classroom_id' => 3, 'professor_id' => 5,  'pensum_course_id' => 22, 'unit' => 4],

            // ==========================================
            // CLASSROOM 4 — Tercero Básico Sección A
            // Pénsum 3 — pensum_course_ids 23-33
            // ==========================================
            ['classroom_id' => 4, 'professor_id' => 1,  'pensum_course_id' => 23, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 1,  'pensum_course_id' => 23, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 1,  'pensum_course_id' => 23, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 1,  'pensum_course_id' => 23, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 12, 'pensum_course_id' => 24, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 12, 'pensum_course_id' => 24, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 12, 'pensum_course_id' => 24, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 12, 'pensum_course_id' => 24, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 4,  'pensum_course_id' => 25, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 4,  'pensum_course_id' => 25, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 4,  'pensum_course_id' => 25, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 4,  'pensum_course_id' => 25, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 8,  'pensum_course_id' => 26, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 8,  'pensum_course_id' => 26, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 8,  'pensum_course_id' => 26, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 8,  'pensum_course_id' => 26, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 11, 'pensum_course_id' => 27, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 11, 'pensum_course_id' => 27, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 11, 'pensum_course_id' => 27, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 11, 'pensum_course_id' => 27, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 3,  'pensum_course_id' => 28, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 3,  'pensum_course_id' => 28, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 3,  'pensum_course_id' => 28, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 3,  'pensum_course_id' => 28, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 9,  'pensum_course_id' => 29, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 9,  'pensum_course_id' => 29, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 9,  'pensum_course_id' => 29, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 9,  'pensum_course_id' => 29, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 10, 'pensum_course_id' => 30, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 10, 'pensum_course_id' => 30, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 10, 'pensum_course_id' => 30, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 10, 'pensum_course_id' => 30, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 8,  'pensum_course_id' => 31, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 8,  'pensum_course_id' => 31, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 8,  'pensum_course_id' => 31, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 8,  'pensum_course_id' => 31, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 7,  'pensum_course_id' => 32, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 7,  'pensum_course_id' => 32, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 7,  'pensum_course_id' => 32, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 7,  'pensum_course_id' => 32, 'unit' => 4],
            ['classroom_id' => 4, 'professor_id' => 5,  'pensum_course_id' => 33, 'unit' => 1],
            ['classroom_id' => 4, 'professor_id' => 5,  'pensum_course_id' => 33, 'unit' => 2],
            ['classroom_id' => 4, 'professor_id' => 5,  'pensum_course_id' => 33, 'unit' => 3],
            ['classroom_id' => 4, 'professor_id' => 5,  'pensum_course_id' => 33, 'unit' => 4],

            // ==========================================
            // CLASSROOM 5 — Tercero Básico Sección B
            // Pénsum 3 — pensum_course_ids 23-33
            // ==========================================
            ['classroom_id' => 5, 'professor_id' => 1,  'pensum_course_id' => 23, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 1,  'pensum_course_id' => 23, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 1,  'pensum_course_id' => 23, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 1,  'pensum_course_id' => 23, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 12, 'pensum_course_id' => 24, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 12, 'pensum_course_id' => 24, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 12, 'pensum_course_id' => 24, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 12, 'pensum_course_id' => 24, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 4,  'pensum_course_id' => 25, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 4,  'pensum_course_id' => 25, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 4,  'pensum_course_id' => 25, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 4,  'pensum_course_id' => 25, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 4,  'pensum_course_id' => 26, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 4,  'pensum_course_id' => 26, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 4,  'pensum_course_id' => 26, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 4,  'pensum_course_id' => 26, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 11, 'pensum_course_id' => 27, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 11, 'pensum_course_id' => 27, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 11, 'pensum_course_id' => 27, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 11, 'pensum_course_id' => 27, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 3,  'pensum_course_id' => 28, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 3,  'pensum_course_id' => 28, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 3,  'pensum_course_id' => 28, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 3,  'pensum_course_id' => 28, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 9,  'pensum_course_id' => 29, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 9,  'pensum_course_id' => 29, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 9,  'pensum_course_id' => 29, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 9,  'pensum_course_id' => 29, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 10, 'pensum_course_id' => 30, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 10, 'pensum_course_id' => 30, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 10, 'pensum_course_id' => 30, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 10, 'pensum_course_id' => 30, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 8,  'pensum_course_id' => 31, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 8,  'pensum_course_id' => 31, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 8,  'pensum_course_id' => 31, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 8,  'pensum_course_id' => 31, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 6,  'pensum_course_id' => 32, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 6,  'pensum_course_id' => 32, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 6,  'pensum_course_id' => 32, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 6,  'pensum_course_id' => 32, 'unit' => 4],
            ['classroom_id' => 5, 'professor_id' => 5,  'pensum_course_id' => 33, 'unit' => 1],
            ['classroom_id' => 5, 'professor_id' => 5,  'pensum_course_id' => 33, 'unit' => 2],
            ['classroom_id' => 5, 'professor_id' => 5,  'pensum_course_id' => 33, 'unit' => 3],
            ['classroom_id' => 5, 'professor_id' => 5,  'pensum_course_id' => 33, 'unit' => 4],

            // ==========================================
            // CLASSROOM 6 — Cuarto Bachillerato en Ciencias y Letras Sección A
            // Pénsum 4 — pensum_course_ids 34-43
            // ==========================================
            ['classroom_id' => 6, 'professor_id' => 3,  'pensum_course_id' => 34, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 3,  'pensum_course_id' => 34, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 3,  'pensum_course_id' => 34, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 3,  'pensum_course_id' => 34, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 12, 'pensum_course_id' => 35, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 12, 'pensum_course_id' => 35, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 12, 'pensum_course_id' => 35, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 12, 'pensum_course_id' => 35, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 5,  'pensum_course_id' => 36, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 5,  'pensum_course_id' => 36, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 5,  'pensum_course_id' => 36, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 5,  'pensum_course_id' => 36, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 4,  'pensum_course_id' => 37, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 4,  'pensum_course_id' => 37, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 4,  'pensum_course_id' => 37, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 4,  'pensum_course_id' => 37, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 11, 'pensum_course_id' => 38, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 11, 'pensum_course_id' => 38, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 11, 'pensum_course_id' => 38, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 11, 'pensum_course_id' => 38, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 4,  'pensum_course_id' => 39, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 4,  'pensum_course_id' => 39, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 4,  'pensum_course_id' => 39, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 4,  'pensum_course_id' => 39, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 8,  'pensum_course_id' => 40, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 8,  'pensum_course_id' => 40, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 8,  'pensum_course_id' => 40, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 8,  'pensum_course_id' => 40, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 3,  'pensum_course_id' => 41, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 3,  'pensum_course_id' => 41, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 3,  'pensum_course_id' => 41, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 3,  'pensum_course_id' => 41, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 2,  'pensum_course_id' => 42, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 2,  'pensum_course_id' => 42, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 2,  'pensum_course_id' => 42, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 2,  'pensum_course_id' => 42, 'unit' => 4],
            ['classroom_id' => 6, 'professor_id' => 6,  'pensum_course_id' => 43, 'unit' => 1],
            ['classroom_id' => 6, 'professor_id' => 6,  'pensum_course_id' => 43, 'unit' => 2],
            ['classroom_id' => 6, 'professor_id' => 6,  'pensum_course_id' => 43, 'unit' => 3],
            ['classroom_id' => 6, 'professor_id' => 6,  'pensum_course_id' => 43, 'unit' => 4],

            // ==========================================
            // CLASSROOM 7 — Quinto Bachillerato en Ciencias y Letras Sección A
            // Pénsum 5 — pensum_course_ids 44-53
            // ==========================================
            ['classroom_id' => 7, 'professor_id' => 1,  'pensum_course_id' => 44, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 1,  'pensum_course_id' => 44, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 1,  'pensum_course_id' => 44, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 1,  'pensum_course_id' => 44, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 12, 'pensum_course_id' => 45, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 12, 'pensum_course_id' => 45, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 12, 'pensum_course_id' => 45, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 12, 'pensum_course_id' => 45, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 5,  'pensum_course_id' => 46, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 5,  'pensum_course_id' => 46, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 5,  'pensum_course_id' => 46, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 5,  'pensum_course_id' => 46, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 4,  'pensum_course_id' => 47, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 4,  'pensum_course_id' => 47, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 4,  'pensum_course_id' => 47, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 4,  'pensum_course_id' => 47, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 7,  'pensum_course_id' => 48, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 7,  'pensum_course_id' => 48, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 7,  'pensum_course_id' => 48, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 7,  'pensum_course_id' => 48, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 11, 'pensum_course_id' => 49, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 11, 'pensum_course_id' => 49, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 11, 'pensum_course_id' => 49, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 11, 'pensum_course_id' => 49, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 8,  'pensum_course_id' => 50, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 8,  'pensum_course_id' => 50, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 8,  'pensum_course_id' => 50, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 8,  'pensum_course_id' => 50, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 11, 'pensum_course_id' => 51, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 11, 'pensum_course_id' => 51, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 11, 'pensum_course_id' => 51, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 11, 'pensum_course_id' => 51, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 8,  'pensum_course_id' => 52, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 8,  'pensum_course_id' => 52, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 8,  'pensum_course_id' => 52, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 8,  'pensum_course_id' => 52, 'unit' => 4],
            ['classroom_id' => 7, 'professor_id' => 3,  'pensum_course_id' => 53, 'unit' => 1],
            ['classroom_id' => 7, 'professor_id' => 3,  'pensum_course_id' => 53, 'unit' => 2],
            ['classroom_id' => 7, 'professor_id' => 3,  'pensum_course_id' => 53, 'unit' => 3],
            ['classroom_id' => 7, 'professor_id' => 3,  'pensum_course_id' => 53, 'unit' => 4],

            // ==========================================
            // CLASSROOM 8 — Cuarto Perito Contador Sección A
            // Pénsum 6 — pensum_course_ids 54-62
            // ==========================================
            ['classroom_id' => 8, 'professor_id' => 6,  'pensum_course_id' => 54, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 6,  'pensum_course_id' => 54, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 6,  'pensum_course_id' => 54, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 6,  'pensum_course_id' => 54, 'unit' => 4],
            ['classroom_id' => 8, 'professor_id' => 7,  'pensum_course_id' => 55, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 7,  'pensum_course_id' => 55, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 7,  'pensum_course_id' => 55, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 7,  'pensum_course_id' => 55, 'unit' => 4],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 56, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 56, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 56, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 56, 'unit' => 4],
            ['classroom_id' => 8, 'professor_id' => 12, 'pensum_course_id' => 57, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 12, 'pensum_course_id' => 57, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 12, 'pensum_course_id' => 57, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 12, 'pensum_course_id' => 57, 'unit' => 4],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 58, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 58, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 58, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 58, 'unit' => 4],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 59, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 59, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 59, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 2,  'pensum_course_id' => 59, 'unit' => 4],
            ['classroom_id' => 8, 'professor_id' => 11, 'pensum_course_id' => 60, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 11, 'pensum_course_id' => 60, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 11, 'pensum_course_id' => 60, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 11, 'pensum_course_id' => 60, 'unit' => 4],
            ['classroom_id' => 8, 'professor_id' => 11, 'pensum_course_id' => 61, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 11, 'pensum_course_id' => 61, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 11, 'pensum_course_id' => 61, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 11, 'pensum_course_id' => 61, 'unit' => 4],
            ['classroom_id' => 8, 'professor_id' => 5,  'pensum_course_id' => 62, 'unit' => 1],
            ['classroom_id' => 8, 'professor_id' => 5,  'pensum_course_id' => 62, 'unit' => 2],
            ['classroom_id' => 8, 'professor_id' => 5,  'pensum_course_id' => 62, 'unit' => 3],
            ['classroom_id' => 8, 'professor_id' => 5,  'pensum_course_id' => 62, 'unit' => 4],

            // ==========================================
            // CLASSROOM 9 — Quinto Perito Contador Sección A
            // Pénsum 7 — pensum_course_ids 63-71
            // ==========================================
            ['classroom_id' => 9, 'professor_id' => 6,  'pensum_course_id' => 63, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 6,  'pensum_course_id' => 63, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 6,  'pensum_course_id' => 63, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 6,  'pensum_course_id' => 63, 'unit' => 4],
            ['classroom_id' => 9, 'professor_id' => 7,  'pensum_course_id' => 64, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 7,  'pensum_course_id' => 64, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 7,  'pensum_course_id' => 64, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 7,  'pensum_course_id' => 64, 'unit' => 4],
            ['classroom_id' => 9, 'professor_id' => 12, 'pensum_course_id' => 65, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 12, 'pensum_course_id' => 65, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 12, 'pensum_course_id' => 65, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 12, 'pensum_course_id' => 65, 'unit' => 4],
            ['classroom_id' => 9, 'professor_id' => 6,  'pensum_course_id' => 66, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 6,  'pensum_course_id' => 66, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 6,  'pensum_course_id' => 66, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 6,  'pensum_course_id' => 66, 'unit' => 4],
            ['classroom_id' => 9, 'professor_id' => 11, 'pensum_course_id' => 67, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 11, 'pensum_course_id' => 67, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 11, 'pensum_course_id' => 67, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 11, 'pensum_course_id' => 67, 'unit' => 4],
            ['classroom_id' => 9, 'professor_id' => 12, 'pensum_course_id' => 68, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 12, 'pensum_course_id' => 68, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 12, 'pensum_course_id' => 68, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 12, 'pensum_course_id' => 68, 'unit' => 4],
            ['classroom_id' => 9, 'professor_id' => 2,  'pensum_course_id' => 69, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 2,  'pensum_course_id' => 69, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 2,  'pensum_course_id' => 69, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 2,  'pensum_course_id' => 69, 'unit' => 4],
            ['classroom_id' => 9, 'professor_id' => 5,  'pensum_course_id' => 70, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 5,  'pensum_course_id' => 70, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 5,  'pensum_course_id' => 70, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 5,  'pensum_course_id' => 70, 'unit' => 4],
            ['classroom_id' => 9, 'professor_id' => 5,  'pensum_course_id' => 71, 'unit' => 1],
            ['classroom_id' => 9, 'professor_id' => 5,  'pensum_course_id' => 71, 'unit' => 2],
            ['classroom_id' => 9, 'professor_id' => 5,  'pensum_course_id' => 71, 'unit' => 3],
            ['classroom_id' => 9, 'professor_id' => 5,  'pensum_course_id' => 71, 'unit' => 4],

            // ==========================================
            // CLASSROOM 10 — Sexto Perito Contador Sección A
            // Pénsum 8 — pensum_course_ids 72-81 (solo 3 unidades)
            // ==========================================
            ['classroom_id' => 10, 'professor_id' => 6,  'pensum_course_id' => 72, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 6,  'pensum_course_id' => 72, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 6,  'pensum_course_id' => 72, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 7,  'pensum_course_id' => 73, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 7,  'pensum_course_id' => 73, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 7,  'pensum_course_id' => 73, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 74, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 74, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 74, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 3,  'pensum_course_id' => 75, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 3,  'pensum_course_id' => 75, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 3,  'pensum_course_id' => 75, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 3,  'pensum_course_id' => 76, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 3,  'pensum_course_id' => 76, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 3,  'pensum_course_id' => 76, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 77, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 77, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 77, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 12, 'pensum_course_id' => 78, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 12, 'pensum_course_id' => 78, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 12, 'pensum_course_id' => 78, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 79, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 79, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 2,  'pensum_course_id' => 79, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 5,  'pensum_course_id' => 80, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 5,  'pensum_course_id' => 80, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 5,  'pensum_course_id' => 80, 'unit' => 3],
            ['classroom_id' => 10, 'professor_id' => 11, 'pensum_course_id' => 81, 'unit' => 1],
            ['classroom_id' => 10, 'professor_id' => 11, 'pensum_course_id' => 81, 'unit' => 2],
            ['classroom_id' => 10, 'professor_id' => 11, 'pensum_course_id' => 81, 'unit' => 3],
        ];
    }
}
